language: ruby

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6.0-preview1
  - jruby-9.1.16.0

matrix:
  exclude:
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.6.0-preview1
      gemfile: gemfiles/rails_4.2.gemfile
  allow_failures:
    - rvm: 2.6.0-preview1
    - rvm: jruby-9.1.16.0

bundler_args: --without development

sudo: false
