language: ruby

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - jruby-9.1.7.0

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: jruby-9.1.7.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.2.gemfile

bundler_args: --without development
